aggiunta appunti personali
csunibo/logica-per-informatica pull request #1
Opened 2022-06-26 12:42 UTC by bugboy-20

Mi ricordo che erano piaciuti a qualcuno, per cui perché non passarli alle generazioni future?

2022-06-26 19:10 UTC, FoxySeta commented
@bugboy-20 Per controllare se le espressioni latex del tuo md compilano senza installare nulla puoi controllarlo su github:
https://github.com/bugboy-20/logica-per-informatica/blob/main/appunti/assiomi-e-definizioni-teoria-degli-insiemi-diego.md
L'aspetto è quello desiderato?

2022-06-27 13:11 UTC, bugboy-20 commented
grazie del consiglio, evidentemente allora non avevo usato il GFM.

2022-06-28 23:09 UTC, FoxySeta commented
@Flecart rilanceresti i controlli? forse stavolta passano

2022-07-03 11:40 UTC, FoxySeta requested changes
Puoi controllare se i test di compilazione passano anche dalla branch main del tuo fork.

2022-07-03 11:40 UTC, FoxySeta commented on appunti/schema-dimostrazioni-diego.md
> +Per dimostrare ∀x .P (x ) (per ogni x vale P (x )):
Per la compilazione i simboli speciali dovrebbero essere riscritti come latex inline. Abbiamo già considerato l'idea di tollerare tutti i caratteri Unicode ma al momento abbiamo voci contrarie con ragioni comprensibili.

2023-10-02 22:53 UTC, foxyseta commented
Riscoperto questa per la dopo 15 mesi. Sostituito i caratteri unicode con il codice $\LaTeX$ appropriato. Grazie @bugboy-20!

2023-10-02 22:53 UTC, foxyseta approved these changes

2023-10-02 22:53 UTC, merged